[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["@sparticuz/chrome-aws-lambda","puppeteer-core","pg"]

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200

[[scheduled.functions]]
function = "cron-scrape"
cron = "*/10 * * * *"